function onCreate()
    makeLuaSprite('chaotixSky','EXE/Bodrionic.exe/myhorison/horizonsky', -1200, -600)
    scaleObject('chaotixSky',1,1)
    setScrollFactor('chaotixSky',0,0)
    setProperty('chaotixSky.antialiasing', false)
    addLuaSprite('chaotixSky', false)

    makeAnimatedLuaSprite('chaotixSky2', 'EXE/Bodrionic.exe/myhorison/corrupt_background', -1200, -600)
    addAnimationByPrefix('chaotixSky2', 'fuy', 'corrupt background', 24, true)
    objectPlayAnimation('chaotixSky2', 'fuy', true)
    scaleObject('chaotixSky2',1,1)
    setProperty('chaotixSky2.antialiasing', false)
    setScrollFactor('chaotixSky2',0,0)
    setProperty('chaotixSky2.alpha', 0)
    addLuaSprite('chaotixSky2', false)

    makeLuaSprite('chaotixfloor','EXE/Bodrionic.exe/myhorison/horizonFg', -1200, -600)
    scaleObject('chaotixfloor',1,1)
    setScrollFactor('chaotixfloor',1,1)
    setProperty('chaotixfloor.antialiasing', false)
    addLuaSprite('chaotixfloor', false)

    makeLuaSprite('chaotixfloor2','EXE/Bodrionic.exe/myhorison/horizonFuckedUp', -1200, -600)
    scaleObject('chaotixfloor2',1,1)
    setScrollFactor('chaotixfloor2',1,1)
    setProperty('chaotixfloor2.antialiasing', false)
    setProperty('chaotixfloor2.alpha', 0)
    addLuaSprite('chaotixfloor2', false)

    makeAnimatedLuaSprite('Vector', 'EXE/Bodrionic.exe/myhorison/BG_vector', -300, 550)
    addAnimationByPrefix('Vector', 'VectorDance', 'vector bobbing', 24, true)
    addAnimationByPrefix('Vector', 'VectorFear', 'vector fear', 24, true)
    objectPlayAnimation('Vector', 'VectorDance', true)
    scaleObject('Vector',6.5,6.5)
    setProperty('Vector.antialiasing', false)
    setScrollFactor('Vector',1,1)
    addLuaSprite('Vector', false)

    makeAnimatedLuaSprite('Knuckles', 'EXE/Bodrionic.exe/myhorison/BG_knuckles', -50, 550)
    addAnimationByPrefix('Knuckles', 'VectorDance', 'knuckles bobbing', 24, true)
    addAnimationByPrefix('Knuckles', 'KnucklesFear', 'knuckles fear', 24, true)
    objectPlayAnimation('Knuckles', 'KnucklesDance', true)
    scaleObject('Knuckles',6.5,6.5)
    setProperty('Knuckles.antialiasing', false)
    setScrollFactor('Knuckles',1,1)
    addLuaSprite('Knuckles', false)

    makeAnimatedLuaSprite('Mighty', 'EXE/Bodrionic.exe/myhorison/BG_mighty', 600, 600)
    addAnimationByPrefix('Mighty', 'MightyDance', 'mighty bobbing', 24, true)
    addAnimationByPrefix('Mighty', 'MightyFear', 'mighty fear', 24, true)
    objectPlayAnimation('Mighty', 'MightyDance', true)
    scaleObject('Mighty',6,6)
    setProperty('Mighty.antialiasing', false)
    setScrollFactor('Mighty',1,1)
    addLuaSprite('Mighty', false)

    makeAnimatedLuaSprite('Charmy', 'EXE/Bodrionic.exe/myhorison/BG_charmy', 1200, 400)
    addAnimationByPrefix('Charmy', 'CharmyDance', 'charmy bobbing', 24, true)
    addAnimationByPrefix('Charmy', 'CharmyFear', 'charmy fear', 24, true)
    objectPlayAnimation('Charmy', 'CharmyDance', true)
    scaleObject('Charmy',6,6)
    setProperty('Charmy.antialiasing', false)
    setScrollFactor('Charmy',1,1)
    addLuaSprite('Charmy', false)

    makeAnimatedLuaSprite('Amy', 'EXE/Bodrionic.exe/myhorison/BG_amy', 1300, 600)
    addAnimationByPrefix('Amy', 'AmyDance', 'amy bobbing', 24, true)
    addAnimationByPrefix('Amy', 'AmyFear', 'amy fear', 24, true)
    objectPlayAnimation('Amy', 'AmyDance', true)
    scaleObject('Amy',6,6)
    setProperty('Amy.antialiasing', false)
    setScrollFactor('Amy',1,1)
    addLuaSprite('Amy', false)

    makeAnimatedLuaSprite('Espio', 'EXE/Bodrionic.exe/myhorison/BG_espio', 1500, 650)
    addAnimationByPrefix('Espio', 'EspioDance', 'espio bobbing', 24, true)
    addAnimationByPrefix('Espio', 'EspioFear', 'espio fear', 24, true)
    objectPlayAnimation('Espio', 'EspioDance', true)
    scaleObject('Espio',6,6)
    setProperty('Espio.antialiasing', false)
    setScrollFactor('Espio',1,1)
    addLuaSprite('Espio', false)
end